export interface CurrencyData {
  code: string;
  name: string;
  flag: string; // ISO 3166-1 alpha-2 country code
}



export const ALL_CURRENCIES: CurrencyData[] = [
  { code: 'AED', name: 'United Arab Emirates Dirham', flag: 'ae' },
  { code: 'AFN', name: 'Afghan Afghani', flag: 'af' },
  { code: 'ALL', name: 'Albanian Lek', flag: 'al' },
  { code: 'AMD', name: 'Armenian Dram', flag: 'am' },
  { code: 'ANG', name: 'Netherlands Antillean Guilder', flag: 'cw' },
  { code: 'AOA', name: 'Angolan Kwanza', flag: 'ao' },
  { code: 'ARS', name: 'Argentine Peso', flag: 'ar' },
  { code: 'AUD', name: 'Australian Dollar', flag: 'au' },
  { code: 'AWG', name: 'Aruban Florin', flag: 'aw' },
  { code: 'AZN', name: 'Azerbaijani Manat', flag: 'az' },
  { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', flag: 'ba' },
  { code: 'BBD', name: 'Barbadian Dollar', flag: 'bb' },
  { code: 'BDT', name: 'Bangladeshi Taka', flag: 'bd' },
  { code: 'BGN', name: 'Bulgarian Lev', flag: 'bg' },
  { code: 'BHD', name: 'Bahraini Dinar', flag: 'bh' },
  { code: 'BIF', name: 'Burundian Franc', flag: 'bi' },
  { code: 'BMD', name: 'Bermudan Dollar', flag: 'bm' },
  { code: 'BND', name: 'Brunei Dollar', flag: 'bn' },
  { code: 'BOB', name: 'Bolivian Boliviano', flag: 'bo' },
  { code: 'BRL', name: 'Brazilian Real', flag: 'br' },
  { code: 'BSD', name: 'Bahamian Dollar', flag: 'bs' },
  { code: 'BTN', name: 'Bhutanese Ngultrum', flag: 'bt' },
  { code: 'BWP', name: 'Botswanan Pula', flag: 'bw' },
  { code: 'BYN', name: 'Belarusian Ruble', flag: 'by' },
  { code: 'BZD', name: 'Belize Dollar', flag: 'bz' },
  { code: 'CAD', name: 'Canadian Dollar', flag: 'ca' },
  { code: 'CDF', name: 'Congolese Franc', flag: 'cd' },
  { code: 'CHF', name: 'Swiss Franc', flag: 'ch' },
  { code: 'CLP', name: 'Chilean Peso', flag: 'cl' },
  { code: 'CNY', name: 'Chinese Yuan', flag: 'cn' },
  { code: 'COP', name: 'Colombian Peso', flag: 'co' },
  { code: 'CRC', name: 'Costa Rican Colón', flag: 'cr' },
  { code: 'CUP', name: 'Cuban Peso', flag: 'cu' },
  { code: 'CVE', name: 'Cape Verdean Escudo', flag: 'cv' },
  { code: 'CZK', name: 'Czech Koruna', flag: 'cz' },
  { code: 'DJF', name: 'Djiboutian Franc', flag: 'dj' },
  { code: 'DKK', name: 'Danish Krone', flag: 'dk' },
  { code: 'DOP', name: 'Dominican Peso', flag: 'do' },
  { code: 'DZD', name: 'Algerian Dinar', flag: 'dz' },
  { code: 'EGP', name: 'Egyptian Pound', flag: 'eg' },
  { code: 'ERN', name: 'Eritrean Nakfa', flag: 'er' },
  { code: 'ETB', name: 'Ethiopian Birr', flag: 'et' },
  { code: 'EUR', name: 'Euro', flag: 'eu' },
  { code: 'FJD', name: 'Fijian Dollar', flag: 'fj' },
  { code: 'FKP', name: 'Falkland Islands Pound', flag: 'fk' },
  { code: 'FOK', name: 'Faroese Króna', flag: 'fo' },
  { code: 'GBP', name: 'British Pound Sterling', flag: 'gb' },
  { code: 'GEL', name: 'Georgian Lari', flag: 'ge' },
  { code: 'GGP', name: 'Guernsey Pound', flag: 'gg' },
  { code: 'GHS', name: 'Ghanaian Cedi', flag: 'gh' },
  { code: 'GIP', name: 'Gibraltar Pound', flag: 'gi' },
  { code: 'GMD', name: 'Gambian Dalasi', flag: 'gm' },
  { code: 'GNF', name: 'Guinean Franc', flag: 'gn' },
  { code: 'GTQ', name: 'Guatemalan Quetzal', flag: 'gt' },
  { code: 'GYD', name: 'Guyanaese Dollar', flag: 'gy' },
  { code: 'HKD', name: 'Hong Kong Dollar', flag: 'hk' },
  { code: 'HNL', name: 'Honduran Lempira', flag: 'hn' },
  { code: 'HRK', name: 'Croatian Kuna', flag: 'hr' },
  { code: 'HTG', name: 'Haitian Gourde', flag: 'ht' },
  { code: 'HUF', name: 'Hungarian Forint', flag: 'hu' },
  { code: 'IDR', name: 'Indonesian Rupiah', flag: 'id' },
  { code: 'ILS', name: 'Israeli New Shekel', flag: 'il' },
  { code: 'IMP', name: 'Isle of Man Pound', flag: 'im' },
  { code: 'INR', name: 'Indian Rupee', flag: 'in' },
  { code: 'IQD', name: 'Iraqi Dinar', flag: 'iq' },
  { code: 'IRR', name: 'Iranian Rial', flag: 'ir' },
  { code: 'ISK', name: 'Icelandic Króna', flag: 'is' },
  { code: 'JEP', name: 'Jersey Pound', flag: 'je' },
  { code: 'JMD', name: 'Jamaican Dollar', flag: 'jm' },
  { code: 'JOD', name: 'Jordanian Dinar', flag: 'jo' },
  { code: 'JPY', name: 'Japanese Yen', flag: 'jp' },
  { code: 'KES', name: 'Kenyan Shilling', flag: 'ke' },
  { code: 'KGS', name: 'Kyrgystani Som', flag: 'kg' },
  { code: 'KHR', name: 'Cambodian Riel', flag: 'kh' },
  { code: 'KID', name: 'Kiribati Dollar', flag: 'ki' },
  { code: 'KMF', name: 'Comorian Franc', flag: 'km' },
  { code: 'KRW', name: 'South Korean Won', flag: 'kr' },
  { code: 'KWD', name: 'Kuwaiti Dinar', flag: 'kw' },
  { code: 'KYD', name: 'Cayman Islands Dollar', flag: 'ky' },
  { code: 'KZT', name: 'Kazakhstani Tenge', flag: 'kz' },
  { code: 'LAK', name: 'Laotian Kip', flag: 'la' },
  { code: 'LBP', name: 'Lebanese Pound', flag: 'lb' },
  { code: 'LKR', name: 'Sri Lankan Rupee', flag: 'lk' },
  { code: 'LRD', name: 'Liberian Dollar', flag: 'lr' },
  { code: 'LSL', name: 'Lesotho Loti', flag: 'ls' },
  { code: 'LYD', name: 'Libyan Dinar', flag: 'ly' },
  { code: 'MAD', name: 'Moroccan Dirham', flag: 'ma' },
  { code: 'MDL', name: 'Moldovan Leu', flag: 'md' },
  { code: 'MGA', name: 'Malagasy Ariary', flag: 'mg' },
  { code: 'MKD', name: 'Macedonian Denar', flag: 'mk' },
  { code: 'MMK', name: 'Myanmar Kyat', flag: 'mm' },
  { code: 'MNT', name: 'Mongolian Tugrik', flag: 'mn' },
  { code: 'MOP', name: 'Macanese Pataca', flag: 'mo' },
  { code: 'MRU', name: 'Mauritanian Ouguiya', flag: 'mr' },
  { code: 'MUR', name: 'Mauritian Rupee', flag: 'mu' },
  { code: 'MVR', name: 'Maldivian Rufiyaa', flag: 'mv' },
  { code: 'MWK', name: 'Malawian Kwacha', flag: 'mw' },
  { code: 'MXN', name: 'Mexican Peso', flag: 'mx' },
  { code: 'MYR', name: 'Malaysian Ringgit', flag: 'my' },
  { code: 'MZN', name: 'Mozambican Metical', flag: 'mz' },
  { code: 'NAD', name: 'Namibian Dollar', flag: 'na' },
  { code: 'NGN', name: 'Nigerian Naira', flag: 'ng' },
  { code: 'NIO', name: 'Nicaraguan Córdoba', flag: 'ni' },
  { code: 'NOK', name: 'Norwegian Krone', flag: 'no' },
  { code: 'NPR', name: 'Nepalese Rupee', flag: 'np' },
  { code: 'NZD', name: 'New Zealand Dollar', flag: 'nz' },
  { code: 'OMR', name: 'Omani Rial', flag: 'om' },
  { code: 'PAB', name: 'Panamanian Balboa', flag: 'pa' },
  { code: 'PEN', name: 'Peruvian Sol', flag: 'pe' },
  { code: 'PGK', name: 'Papua New Guinean Kina', flag: 'pg' },
  { code: 'PHP', name: 'Philippine Peso', flag: 'ph' },
  { code: 'PKR', name: 'Pakistani Rupee', flag: 'pk' },
  { code: 'PLN', name: 'Polish Zloty', flag: 'pl' },
  { code: 'PYG', name: 'Paraguayan Guarani', flag: 'py' },
  { code: 'QAR', name: 'Qatari Rial', flag: 'qa' },
  { code: 'RON', name: 'Romanian Leu', flag: 'ro' },
  { code: 'RSD', name: 'Serbian Dinar', flag: 'rs' },
  { code: 'RUB', name: 'Russian Ruble', flag: 'ru' },
  { code: 'RWF', name: 'Rwandan Franc', flag: 'rw' },
  { code: 'SAR', name: 'Saudi Riyal', flag: 'sa' },
  { code: 'SBD', name: 'Solomon Islands Dollar', flag: 'sb' },
  { code: 'SCR', name: 'Seychellois Rupee', flag: 'sc' },
  { code: 'SDG', name: 'Sudanese Pound', flag: 'sd' },
  { code: 'SEK', name: 'Swedish Krona', flag: 'se' },
  { code: 'SGD', name: 'Singapore Dollar', flag: 'sg' },
  { code: 'SHP', name: 'St. Helena Pound', flag: 'sh' },
  { code: 'SLL', name: 'Sierra Leonean Leone', flag: 'sl' },
  { code: 'SOS', name: 'Somali Shilling', flag: 'so' },
  { code: 'SRD', name: 'Surinamese Dollar', flag: 'sr' },
  { code: 'SSP', name: 'South Sudanese Pound', flag: 'ss' },
  { code: 'STN', name: 'São Tomé & Príncipe Dobra', flag: 'st' },
  { code: 'SYP', name: 'Syrian Pound', flag: 'sy' },
  { code: 'SZL', name: 'Eswatini Lilangeni', flag: 'sz' },
  { code: 'THB', name: 'Thai Baht', flag: 'th' },
  { code: 'TJS', name: 'Tajikistani Somoni', flag: 'tj' },
  { code: 'TMT', name: 'Turkmenistani Manat', flag: 'tm' },
  { code: 'TND', name: 'Tunisian Dinar', flag: 'tn' },
  { code: 'TOP', name: 'Tongan Paʻanga', flag: 'to' },
  { code: 'TRY', name: 'Turkish Lira', flag: 'tr' },
  { code: 'TTD', name: 'Trinidad & Tobago Dollar', flag: 'tt' },
  { code: 'TVD', name: 'Tuvaluan Dollar', flag: 'tv' },
  { code: 'TWD', name: 'New Taiwan Dollar', flag: 'tw' },
  { code: 'TZS', name: 'Tanzanian Shilling', flag: 'tz' },
  { code: 'UAH', name: 'Ukrainian Hryvnia', flag: 'ua' },
  { code: 'UGX', name: 'Ugandan Shilling', flag: 'ug' },
  { code: 'USD', name: 'United States Dollar', flag: 'us' },
  { code: 'UYU', name: 'Uruguayan Peso', flag: 'uy' },
  { code: 'UZS', name: 'Uzbekistani Som', flag: 'uz' },
  { code: 'VES', name: 'Venezuelan Bolívar Soberano', flag: 've' },
  { code: 'VND', name: 'Vietnamese Dong', flag: 'vn' },
  { code: 'VUV', name: 'Vanuatu Vatu', flag: 'vu' },
  { code: 'WST', name: 'Samoan Tala', flag: 'ws' },
  { code: 'XAF', name: 'Central African CFA Franc', flag: 'cm' },
  { code: 'XCD', name: 'East Caribbean Dollar', flag: 'ag' },
  { code: 'XDR', name: 'Special Drawing Rights', flag: 'un' },
  { code: 'XOF', name: 'West African CFA Franc', flag: 'sn' },
  { code: 'XPF', name: 'CFP Franc', flag: 'pf' },
  { code: 'YER', name: 'Yemeni Rial', flag: 'ye' },
  { code: 'ZAR', name: 'South African Rand', flag: 'za' },
  { code: 'ZMW', name: 'Zambian Kwacha', flag: 'zm' },
  { code: 'ZWL', name: 'Zimbabwean Dollar', flag: 'zw' },
];

export const getCurrencyData = (code: string): CurrencyData => {
  return ALL_CURRENCIES.find(c => c.code === code) || { code, name: code, flag: 'un' };
};
